### ISSUE TITLE
Creating folder-dropbox and folder-gdrive

### ISSUE THREAD

**Issue by horosgrisa** [NitruxSA/breeze-icon-theme#155]
I propose to add folder-dropbox and folder-gdrive, it's can be very useful for users of these apps.

**Comment by UriHerrera** [comment]
Neither of these can be added to the mainline theme but I can add them to a separate branch.

**Comment by horosgrisa** [comment]
That would be great. You can create separate branch for this?

**Comment by DarkknightAK** [comment]
done.

**Comment by horosgrisa** [comment]
@DarkknightAK You can create similar icon for ownCloud?
