### ISSUE TITLE
[Icon request] Skype

### ISSUE THREAD

**Issue by Steinhagen** [NitruxSA/breeze-icon-theme#244]
It would be nice to have an application icon and status icons for Skype in the trademark branch.

**Comment by UriHerrera** [comment]
Skype status icons can't themed by any icon theme only the application icon.

**Comment by Steinhagen** [comment]
Since the status icons can't be themed and with varlesh's recent commit containing the Skype icon, I believe that this issue can now be closed. Thanks! :)
