### ISSUE TITLE
Name mismatch for new visibility icons?

### ISSUE THREAD

**Issue by aelog** [NitruxSA/breeze-icon-theme#258]
Not sure whether this is an actual issue, but the new visibility icons (pull request #255) have different names for different sizes:

* 16 px -> visibility.svg
* 22 px -> visible.svg

This happens both in Breeze and Breeze dark. I guess the proper name would be visibility for both sizes.

**Comment by UriHerrera** [comment]
Which one is the one that's used? @DarkknightAK

**Comment by UriHerrera** [comment]
I renamed it.
