### ISSUE TITLE
[Icon request] Subtitle Composer, Synfig Studio MineType

### ISSUE THREAD

**Issue by aldy-art** [NitruxSA/breeze-icon-theme#298]
Hi, some missing icons that I saw. 
- Subtitle Composer (subtitlecomposer) => KDE Subtitle Editor.

- Synfig Studio (synfig_icon) => Animation program.
- *.sif (application/x-sif) => MineTypes for Synfig documents.

If its not posible the icon for Synfig Studio, at least consider the *.sif MineType because these files don't show any icon in dolphin, just the filename. I'ts really ugly.

**Comment by aldy-art** [comment]
I did an icon for Synfig inspired by the icon from the theme "El general". For the mymetypes I'm using a copy of the breeze icon "application-x-wmf.svg" because Synfig use vectors.
I share this here because somebody may find this usefull.

https://cloud.openmailbox.org/index.php/s/4f62ALnksnFTJxH

PS: I closed the issue by accident. Sorry.

**Comment by DarkknightAK** [comment]
thanks now you can close the issue.

but maybe you are interested to add the other missing breeze icons. feel free to contact me.

cheers
Andreas
