### ISSUE TITLE
Remove non-trademarked icons from trademarks branch

### ISSUE THREAD

**Issue by KAMiKAZOW** [NitruxSA/breeze-icon-theme#304]
Or create a dedicated repo for the trademarked icons.
As a packager I'd like to create an addon package that does not conflict with the distro-provided Breeze icon theme.

**Comment by DarkknightAK** [comment]
I ask at the kde license mailing list how to handle this issue.

**Comment by UriHerrera** [comment]
A dedicated repo is an overkill. The point of the branch is to have the same icons plus the ones we can't add. The distro provided Breeze *should* by all means be the same we provide.

**Comment by KAMiKAZOW** [comment]
Too bad, the changes from Master are not often synced with Trademarks.
As I said: From the POV of a packager, something easily packageable as addon would be nicer to use.

**Comment by UriHerrera** [comment]
You can just package the icons in the trademarks branch and have Breeze as their dependency. It should then just add the extra icons to the Breeze folder.

**Comment by cesasol** [comment]
How about having the index of the trademark branch inherit the base icons

**Comment by KAMiKAZOW** [comment]
That would not help if icons in Master have been tweaked/reworked. If Trademarked inherited Master, only gaps would be filled.
If Trademarked were synced promptly after an update to Master, there would be no problem as well.

Please pick any of these two: Either delete non-trademarked icons from the branch or keep the Trademarked branch in sync but the current situation with outdated non-trademarked icons in the is just bad.

**Comment by UriHerrera** [comment]
Well, pull requests can be made in that case (by anyone) to keep the branch in sync where any of us forgets to sync it.

**Comment by KAMiKAZOW** [comment]
Why should others do a pull request when you just could push your changes to two branches? It's basically no extra work for you.
