### ISSUE TITLE
The "airplane mode" icon is very unclear in 5.5

### ISSUE THREAD

**Issue by mck182** [NitruxSA/breeze-icon-theme#308]
I was wondering what that red icon in Network Manager was, it turns out it's the "airplane mode".

It used to be a plane, please make it a plane-like again, which is a familiar metaphor for this action.

The current icon looks like a compass arrow/needle (like eg. in android google maps) and it looks like that enables/disables gps or something (especially with those beams going up), which makes the meaning of that action not at all clear.

**Comment by UriHerrera** [comment]
Plasma doesn't use the assets form the icon theme. It uses it's own assets.

**Comment by mck182** [comment]
Ok so where do you want those reports filed then?

**Comment by UriHerrera** [comment]
bugs.kde.org

**Comment by mck182** [comment]
Ok but where? I can put it under product plasmashell and component "Theme - Breeze" but do note that this is assigned to Andrew Lake and I don't know if you are aware of those bugs reported there.

Also I was under the impression that Plasma Breeze icons have now been synchronized with the main Breeze iconset to use the same icons everywhere. Is that not the case?

**Comment by UriHerrera** [comment]
There is a VisualDesign flag I think that will notice everyone in the mailing list.
