### ISSUE TITLE
Wrong konversation icon in panels

### ISSUE THREAD

**Issue by Steinhagen** [NitruxSA/breeze-icon-theme#311]
Konversation when it's added to a panel has the wrong icon.
If this problem is on the Konversation developing team and not with breeze, this should be closed as invalid.

![konversationicon](https://cloud.githubusercontent.com/assets/4029937/11251060/70fbf498-8e27-11e5-8251-35131bf952c4.png)

**Comment by UriHerrera** [comment]
It's not wrong. Plasma uses a Konversation icon, to my knowledge this happens with Ktorrent, kGet. The point of these icons is to use them in the system tray but they're being used in the task manager too.
