### ISSUE TITLE
system-shutdown icon 48px should be removed

### ISSUE THREAD

**Issue by guoyunhe** [NitruxSA/breeze-icon-theme#321]
Breeze/apps/48/system-shutdown.svg

It seems very different from the 32px version. And none of other power and session icons has 48px version.
![1](https://cloud.githubusercontent.com/assets/5836790/11370681/850ff6be-92cd-11e5-9613-81361f163aee.png)

**Comment by UriHerrera** [comment]
Because that icon is used in KDE 4 in the kickoff tabs and it's used by Plasma if the Plasma theme doesn't provide these system action icons.The 32px icon is a newer revision, that should be the shutdown icon actually.

**Comment by guoyunhe** [comment]
> The 32px icon is a newer revision, that should be the shutdown icon actually.

This is not true for me:
![1](https://cloud.githubusercontent.com/assets/5836790/11378437/d1599748-92f3-11e5-984a-e4c68cf4aed6.png)

**Comment by guoyunhe** [comment]
If you have to keep it, please make it the same with the 32px one. There is no reason to make it so special. In Oxygen theme, all system-shutdown icons have the same design.

![1](https://cloud.githubusercontent.com/assets/5836790/11378861/fca860ee-92f5-11e5-992e-5df3f191aad7.png)
