### ISSUE TITLE
[Icon request] Steam

### ISSUE THREAD

**Issue by artur9010** [NitruxSA/breeze-icon-theme#343]

**Comment by UriHerrera** [comment]
Duplicate of: https://github.com/NitruxSA/breeze-icon-theme/issues/278

**Comment by KAMiKAZOW** [comment]
There is no Steam icon in the trademark branch.

**Comment by UriHerrera** [comment]
There was one. I don't know why it was deleted: https://gist.github.com/UriHerrera/649aeedcb9468cfeb06a

**Comment by KAMiKAZOW** [comment]
Then add it to the trademarks branch again ;)
