### ISSUE TITLE
[Icon request] GNU Octave

### ISSUE THREAD

**Issue by rocketsound** [NitruxSA/breeze-icon-theme#54]
I can't find GNU Octave in the list: https://www.gnu.org/software/octave/
You can find the default icon of this program on the top right of the linked website

**Comment by UriHerrera** [comment]
As this is not a KDE software the Breeze theme doesn't *have* to include and icon for it. **But** I reckon is a somewhat popular software for those studying the area or doing work related to it and they may be using KDE. So, it should be up to the community and/or collaborators to include an icon for this.
